apiVersion: v1
kind: Secret
metadata:
  name: {{ include "delta-sharing-ui.fullname" . }}-secrets
  labels:
    {{- include "delta-sharing-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "delta-sharing-ui.databaseUrl" . | quote }}
  JWT_SECRET: {{ include "delta-sharing-ui.jwtSecret" . | quote }}
  ENCRYPTION_KEY: {{ include "delta-sharing-ui.encryptionKey" . | quote }}
  {{- if .Values.storage.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.storage.aws.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.storage.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.aws.secretAccessKey | quote }}
  {{- end }}
  {{- if .Values.storage.azure.accountName }}
  AZURE_STORAGE_ACCOUNT: {{ .Values.storage.azure.accountName | quote }}
  {{- end }}
  {{- if .Values.storage.azure.accountKey }}
  AZURE_STORAGE_KEY: {{ .Values.storage.azure.accountKey | quote }}
  {{- end }}
  {{- if .Values.storage.gcs.keyFile }}
  GCS_KEY_FILE: {{ .Values.storage.gcs.keyFile | quote }}
  {{- end }}









